### ISSUE TITLE
Red Window of JS Error

### ISSUE THREAD

**Issue by kookma** [EvidentlyCube/TW5-TiddlerCompletion#6] opened 2022-12-16 09:20 UTC
Using Auto Complete on a field value I get the below error.

![img_146_msedge](https://user-images.githubusercontent.com/830394/208064549-4807f99a-3ffd-493f-b5db-3821733d02ac.gif)
![image](https://user-images.githubusercontent.com/830394/208062602-57ef0c45-58ff-44e5-bbd4-28fd60887f74.png)

To reproduce

1. open https://evidentlycube.github.io/TW5-PluginShowcase
2. install CodeMirror and save (may have to save locally)
3. download   [Dive into Deep Learning.zip](https://github.com/EvidentlyCube/TW5-AutoComplete/files/10244341/Dive.into.Deep.Learning.zip) tiddler and unzip and drop into https://evidentlycube.github.io/TW5-PluginShowcase
4. Open the `Dive into Deep Learning` tiddler
5. In one of field start typing `[[..`
6. See the error

**Comment by EvidentlyCube** [comment] 2022-12-16 11:07
@kookma Just looking at the error it's certainly not something happening right in my code since I don't ever work with a property named `chunkSize`. If code mirror is required then I have an idea what might be wrong though. Investigation time!

**Comment by EvidentlyCube** [comment] 2023-01-21 10:53
This should be fixed in latest 1.0.15 release. This was caused by the Code Mirror integration not verifying that the code mirror is focused when handling events.

**Closed as completed by EvidentlyCube** 2023-01-21 10:53 UTC
